Update release manifests

diff --git a/3.Transitional-microservices-architecture/release/kubernetes-manifests.yaml b/3.Transitional-microservices-architecture/release/kubernetes-manifests.yaml
--- a/3.Transitional-microservices-architecture/release/kubernetes-manifests.yaml
+++ b/3.Transitional-microservices-architecture/release/kubernetes-manifests.yaml
@@ -14,12 +14,12 @@ spec:
       serviceAccountName: default
       containers:
         - name: server
-          image: gcr.io/architect-demos/backendservice:v3.0
+          image: gcr.io/YOUR_PROJECT_ID/backendservice:v3.1
           ports:
           - containerPort: 50052
           env:
           - name: PROJECT_ID
-            value: "architect-demos"
+            value: "YOUR_PROJECT_ID"
           resources:
             requests:
               cpu: 100m
@@ -59,7 +59,7 @@ spec:
       serviceAccountName: default
       containers:
         - name: server
-          image: gcr.io/architect-demos/frontend:v3.0
+          image: gcr.io/YOUR_PROJECT_ID/frontend:v3.0
           ports:
           - containerPort: 8080
           env:
@@ -119,12 +119,12 @@ spec:
       serviceAccountName: default
       containers:
         - name: server
-          image: gcr.io/architect-demos/updateservice:v3.0
+          image: gcr.io/YOUR_PROJECT_ID/updateservice:v3.0
           ports:
           - containerPort: 50053
           env:
           - name: PROJECT_ID
-            value: "architect-demos"
+            value: "YOUR_PROJECT_ID"
           resources:
             requests:
               cpu: 100m
@@ -145,3 +145,55 @@ spec:
   - name: grpc
     port: 50053
     targetPort: 50053
+---
+apiVersion: apps/v1
+kind: Deployment
+metadata:
+  name: loadgenerator
+spec:
+  selector:
+    matchLabels:
+      app: loadgenerator
+  replicas: 1
+  template:
+    metadata:
+      labels:
+        app: loadgenerator
+      annotations:
+        sidecar.istio.io/rewriteAppHTTPProbers: "true"
+    spec:
+      serviceAccountName: default
+      terminationGracePeriodSeconds: 5
+      restartPolicy: Always
+      initContainers:
+      - command:
+        - /bin/sh
+        - -exc
+        - |
+          echo "Init container pinging frontend: ${FRONTEND_ADDR}..."
+          STATUSCODE=$(wget --server-response http://${FRONTEND_ADDR} 2>&1 | awk '/^  HTTP/{print $2}')
+          if test $STATUSCODE -ne 200; then
+              echo "Error: Could not reach frontend - Status code: ${STATUSCODE}"
+              exit 1
+          fi
+        name: frontend-check
+        image: busybox:latest
+        env:
+        - name: FRONTEND_ADDR
+          value: "frontend:80"
+      containers:
+      - name: main
+        image: gcr.io/YOUR_PROJECT_ID/loadgenerator:v4.0
+        env:
+        - name: FRONTEND_ADDR
+          value: "frontend:80"
+        - name: USERS
+          value: "10"
+        resources:
+          requests:
+            cpu: 300m
+            memory: 256Mi
+          limits:
+            cpu: 500m
+            memory: 512Mi
+
